### PR TITLE
Some updates to help with symfony/ux maintenance

### PR DESCRIPTION
**Pull request by kbond**
Ping @smnandre, @webmamba

### CODE REVIEW

**Comment by smnandre** [comment]
We just need to check all our "tags" are in "dddddd" color :))

**Comment by kbond** [comment]
> We just need to check all our "tags" are in "dddddd" color :))

They are

**Review by chalasr — APPROVED** [review]

**Review by WebMamba — APPROVED** [review]
Great I start doing that by hand it's much better like this!

**Comment by WebMamba** [comment]
Is it carsonbot in charge to close fixed issue ?

**Comment by kbond** [comment]
> Is it carsonbot in charge to close fixed issue ?

No, github should do this automatically.

**Pull request merged**
