### PR TITLE
Avoid closing missing translation issues as stale

### PR DESCRIPTION
**Pull request by stof**
If those get closed, the next run of carsonbot would create a new one anyway.

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]

**Comment by stof** [comment]
@Nyholm looks like your recent update of dependencies forced the usage of composer 2 without making the psalm github actions compatible with it (as it looks like it uses composer 1)

**Comment by Nyholm** [comment]
Yeah. I fixed it here: https://github.com/symfony-tools/carsonbot/pull/205

I wanted to have somewhat clean PRs

**Comment by Nyholm** [comment]
Could I ask you to rebase again to make sure CI is green?

**Comment by stof** [comment]
@Nyholm done

**Comment by Nyholm** [comment]
Thank you!

**Comment by stof** [comment]
@weaverryan has this change been deployed to the prod version of Carsonbot ? I still see it closing translation tickets as stalled.

**Pull request merged**
